config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  resources :cities, only: :show do
    post :attractions, on: :member
    post :search, on: :collection
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, except: :search
  before_action :get_attractions, except: :search

  def search
    if params.dig(:city_search).present?
      @cities = City.where('lower(name) LIKE ?', "#{params[:city_search].downcase}%").limit(10)
    else 
      @cities = []
    end
    render turbo_stream: turbo_stream.update("search_results", partial: "cities/search_results", locals: { cities: @cities })
  end

  def attractions
    render turbo_stream: turbo_stream.update('attractions', partial: 'cities/attractions', locals: { attractions: @attractions })
  end
  
  private
  def set_city
    @city = City.find(params[:id])
  end

  def get_attractions
    query = {location: "#{@city.name}, #{@city.state}", limit: 10, categories: params[:category] || 'restaurants'}
    headers = {Authorization: "Bearer #{ENV['YELP_API_KEY']}"}
    @attractions = HTTParty.get("https://api.yelp.com/v3/businesses/search", query: query, headers: headers)['businesses']      
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cities/_attractions.html.erb
<% if !attractions.empty? %>
  <ol>
    <% attractions.each do |attraction| %>
      <li><%= attraction['name'] %></li>
    <% end %>
  </ol>
<% else %>
  <p>Sorry, we couldn't find anything for that category</p>
<% end %>

app/views/cities/_search_form.html.erb
<%= form_with url: search_cities_path, method: :post do |form| %>
  <%= form.search_field :city_search, value: params[:city_search], placeholder: "Enter your city", oninput: "this.form.requestSubmit()" %>
<% end %>

<div id="search_results"></div>

app/views/cities/_search_results.html.erb
<% cities.each do |city| %>
  <p style='margin: 0.25rem;'><%= link_to "#{city.name}, #{city.state}", city %></p>
<% end %>

app/views/cities/show.html.erb
<turbo-frame id="city" target="_top">
  <h3 style="margin-top: 0rem; margin-bottom: 0.5rem;"><%= "#{@city.name}, #{@city.state}"%></h3>
  <%= link_to 'Change City', root_path, 'data-turbo-frame' => '_self' %>
</turbo-frame>
<%= form_with url: attractions_city_path(@city), method: :post, html: {style: "padding-top: 0.75rem;"}  do |form| %>
  <%= form.select(:category, 
    [['Restaurants', 'restaurants'], ['Axe Throwing', 'axethrowing'], ['Spas', 'spas'], ['Nightlife', 'nightlife'], ['Art Galleries', 'galleries']],
    { selected: (params[:category] || 'restaurants') },
    { onchange: "this.form.requestSubmit()" }
  ) %>
<% end %>
<div id="attractions">
  <%= render partial: "cities/attractions", locals: {attractions: @attractions} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Top10</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="padding: 0.5rem">
    <h1><%= link_to "Top 10", root_path, style: "text-decoration: none; color: black;" %></h1>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<turbo-frame id="city" target="_top">
  <%= render "cities/search_form" %>
</turbo-frame>